import pytest


def test_get_report_service(client, report_uri, create_orders):
    response = client.get(report_uri)
    report = response.json
    pytest.assume(response.status.startswith("200"))
    pytest.assume(report["most_requested_ingredient"])
    pytest.assume(report["most_requested_ingredient"]["name"])
    pytest.assume(report["most_requested_ingredient"]["price"])
    pytest.assume(report["most_requested_ingredient"]["count"])
    pytest.assume(report["most_requested_beverage"])
    pytest.assume(report["most_requested_beverage"]["name"])
    pytest.assume(report["most_requested_beverage"]["price"])
    pytest.assume(report["most_requested_beverage"]["count"])
    pytest.assume(report["month_with_more_revenue"])
    pytest.assume(report["month_with_more_revenue"]["name"])
    pytest.assume(report["month_with_more_revenue"]["total"])
    pytest.assume(report["top_3_customers"])
    pytest.assume(report["top_3_customers"][0])
    pytest.assume(report["top_3_customers"][0]["dni"])
    pytest.assume(report["top_3_customers"][0]["name"])
    pytest.assume(report["top_3_customers"][0]["address"])
    pytest.assume(report["top_3_customers"][0]["phone"])
    pytest.assume(report["top_3_customers"][0]["total_spent"])
    pytest.assume(report["top_3_customers"][1])
    pytest.assume(report["top_3_customers"][1]["dni"])
    pytest.assume(report["top_3_customers"][1]["name"])
    pytest.assume(report["top_3_customers"][1]["address"])
    pytest.assume(report["top_3_customers"][1]["phone"])
    pytest.assume(report["top_3_customers"][1]["total_spent"])
    pytest.assume(report["top_3_customers"][2])
    pytest.assume(report["top_3_customers"][2]["dni"])
    pytest.assume(report["top_3_customers"][2]["name"])
    pytest.assume(report["top_3_customers"][2]["address"])
    pytest.assume(report["top_3_customers"][2]["phone"])
    pytest.assume(report["top_3_customers"][2]["total_spent"])
