name: CI_Pizza_Planet

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency: 
  group: CI_P_P_${{github.ref}}
  cancel-in-progress: true

jobs:
  install_dependencies:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

  run_lint:
    runs-on: ubuntu-22.04
    needs: [install_dependencies]
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3

      - name: Restoring cached venv
        id: cached_venv
        uses: actions/cache@v3
        with:
          path : .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Run lint
        run: make run_lint

  run_tests:
    runs-on: ubuntu-22.04
    needs: [install_dependencies]
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3

      - name: Restoring cached venv
        id: cached_venv
        uses: actions/cache@v3
        with:
          path : .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Run tests
        run: make run_tests

  run_coverage:
    runs-on: ubuntu-22.04
    needs: [run_lint, run_tests]
    steps:
      - name: Checkout to feature branch
        uses: actions/checkout@v3

      - name: Restoring cached venv
        id: cached_venv
        uses: actions/cache@v3
        with:
          path : .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Run coverage report
        run: make run_coverage_report
      
      - name: Comment coverage
        uses: ewjoachim/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90